2025-01-05 23:04:39,299 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Ari\PycharmProjects\Python\Module12_test\tests_12_4.py", line 27, in test_run
    _runner = runner.Runner(1)
  File "C:\Users\Ari\PycharmProjects\Python\Module12_test\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-05 23:04:39,302 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Ari\PycharmProjects\Python\Module12_test\tests_12_4.py", line 15, in test_walk
    _runner = runner.Runner('Keith', -5)
  File "C:\Users\Ari\PycharmProjects\Python\Module12_test\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
